server:
  port: 8082

spring:
  application:
    name: chat-service

  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: 1

  jpa:
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: update
    show-sql: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

logging:
  level:
    org.springframework.security: TRACE

jwt:
  public-key: classpath:public.pem