server:
  port: 8082

spring:
  application:
    name: chat-service

  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: 1

  jpa:
    properties:
      hibernate:
        format_sql: false
    hibernate:
      ddl-auto: update
    show-sql: false

  data:
    redis:
      host: ${SPRING_DATA_REDIS_HOST:localhost}
      port: ${SPRING_DATA_REDIS_PORT:6379}


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

logging:
  level:
    org.springframework.security: TRACE

jwt:
  public-key: classpath:public.pem